_target_: drone_playground.actions.controllers.velocity.VelocityControl
name: velocity_yaw
input_kind: velocity_yaw
max_speed: 20.0
velocity_gain:
- 3.0
- 3.0
- 5.0
acceleration_limit:
- 6.0
- 6.0
- 6.0
tilt_limit: 0.55
gravity: 9.81
