# @package _global_
defaults:
- /scene@env.scene: lotf_world
- /task@env.task: lotf_hover
- /sensor@env.sensor: none
- /observation@env.observation: lotf_state
- /execution@env.execution: lotf
- /objective: lotf_hover
- _self_
env:
  name: paper/lotf_hover
