# @package _global_
defaults:
- /scene@env.scene: navigation/catalog
- /task@env.task: paper_transfer
- /sensor@env.sensor: paper_uniform
- /observation@env.observation: paper_pointcloud
- /execution@env.execution: acceleration
- /objective: paper_pointcloud
- _self_
env:
  name: paper/pointcloud_navigation
