_target_: drone_playground.simulation.mpc.SamplingMPC
drone: ${simulation.drone}
frequency: ${simulation.method_hz}
samples: 2000
horizon: 25
prediction_seconds: 1.0
device: ${simulation.device}
yaw: 0.0
