# @package _global_
defaults:
- /scene@env.scene: navigation/dynamic
- /task@env.task: navigation
- /sensor@env.sensor: mid360
- /observation@env.observation: navigation_lidar
- /execution@env.execution: velocity_yaw
- /objective: navigation_motion
- _self_
env:
  name: navigation/dynamic_velocity
  task:
    dynamic: true
