# @package _global_
defaults:
- /scene@env.scene: navigation/static
- /task@env.task: navigation
- /sensor@env.sensor: mid360
- /observation@env.observation: navigation_lidar
- /execution@env.execution: velocity_yaw
- /objective: navigation_motion_v2
- _self_
env:
  name: navigation/static_velocity
  task:
    dynamic: false
