# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from drone_playground.simulation.ros_planner import (
    planner_pb2 as drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2,
)

GRPC_GENERATED_VERSION = "1.84.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in drone_playground/simulation/ros_planner/planner_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RosPlannerStub:
    """SI units; world is right-handed ENU, body is FLU. All times are simulation ns."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
            "/drone_playground.ros_planner.v1.RosPlanner/Initialize",
            request_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.InitializeRequest.SerializeToString,
            response_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            _registered_method=True,
        )
        self.Reset = channel.unary_unary(
            "/drone_playground.ros_planner.v1.RosPlanner/Reset",
            request_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
            response_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            _registered_method=True,
        )
        self.Decide = channel.unary_unary(
            "/drone_playground.ros_planner.v1.RosPlanner/Decide",
            request_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.DecideRequest.SerializeToString,
            response_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Decision.FromString,
            _registered_method=True,
        )
        self.Close = channel.unary_unary(
            "/drone_playground.ros_planner.v1.RosPlanner/Close",
            request_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
            response_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Closed.FromString,
            _registered_method=True,
        )


class RosPlannerServicer:
    """SI units; world is right-handed ENU, body is FLU. All times are simulation ns."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RosPlannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Initialize": grpc.unary_unary_rpc_method_handler(
            servicer.Initialize,
            request_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.InitializeRequest.FromString,
            response_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
        ),
        "Reset": grpc.unary_unary_rpc_method_handler(
            servicer.Reset,
            request_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            response_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
        ),
        "Decide": grpc.unary_unary_rpc_method_handler(
            servicer.Decide,
            request_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.DecideRequest.FromString,
            response_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Decision.SerializeToString,
        ),
        "Close": grpc.unary_unary_rpc_method_handler(
            servicer.Close,
            request_deserializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            response_serializer=drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Closed.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "drone_playground.ros_planner.v1.RosPlanner", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "drone_playground.ros_planner.v1.RosPlanner", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RosPlanner:
    """SI units; world is right-handed ENU, body is FLU. All times are simulation ns."""

    @staticmethod
    def Initialize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/drone_playground.ros_planner.v1.RosPlanner/Initialize",
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.InitializeRequest.SerializeToString,
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Reset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/drone_playground.ros_planner.v1.RosPlanner/Reset",
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Decide(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/drone_playground.ros_planner.v1.RosPlanner/Decide",
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.DecideRequest.SerializeToString,
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Close(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/drone_playground.ros_planner.v1.RosPlanner/Close",
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Session.SerializeToString,
            drone__playground_dot_simulation_dot_ros__planner_dot_planner__pb2.Closed.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
