seed: 0
num_envs: 32
policy_updates: 50000
num_timesteps: null
num_evals: 11
development_envs: 32
publish_live: false
max_wall_seconds: 172800
device: gpu
resume: null
warm_start: null
stop_after_updates: null
