_target_: drone_playground.environments.observations.NavigationSensorObservation
name: navigation_lidar
include_goal: true
include_previous_action: true
action_size: 4
history: 4
points_per_frame: 120
channels: 5
near_m: 0.1
far_m: 40.0
