_target_: drone_playground.environments.observations.NavigationSensorObservation
name: navigation_depth
include_goal: true
include_previous_action: true
action_size: 4
history: 4
points_per_frame: 300
channels: 2
near_m: 0.1
far_m: 10.0
