name: racing
freq: 50
duration: 30.0
reference: lsy_course
reference_count: 256
numerical_guard: false
reference_generator:
  _target_: drone_playground.methods.planners.reference.TrajectoryPlan
  name: lsy_course
  amplitude: 1.0
