defaults:
- _self_
- method: learning/ppo
config_version: 3
mode: train
run_id: null
checkpoint: null
source: ''
migration: null
replay:
  directory: null
hydra:
  job:
    chdir: false
  run:
    dir: tmp/hydra/${now:%Y%m%d-%H%M%S}
  sweep:
    dir: tmp/hydra/multirun-${now:%Y%m%d-%H%M%S}
    subdir: ${hydra.job.num}
