# @package _global_
defaults:
- /sensor@env.sensor: none
- /action@env.action: attitude_thrust
- /dynamics@env.dynamics: crazyflow_so_rpy
- _self_
env:
  scene:
    _target_: drone_playground.environments.scenes.empty.EmptyScene
    name: empty
    takeoff:
    - -1.5
    - 1.0
    - 0.07
  task:
    name: tracking
    freq: 50
    duration: 10.0
    reference: figure8
    reference_count: 256
    numerical_guard: false
    reference_generator:
      _target_: drone_playground.environments.tasks.references.ReferenceGenerator
      name: figure8
      amplitude: 1.0
    time_limit_kind: truncation
    policy_evaluator: drone_playground.evaluation.tracking.policy.PolicyEvaluator
    command_distribution:
      kind: reference
      distribution: reference_bank
  observation:
    _target_: drone_playground.environments.observations.state.TrackingObservation
    name: state_reference
    n_samples: 10
    interval: 0.1
  name: tracking
objective:
  _target_: drone_playground.environments.tasks.rewards.TrackingObjective
  name: tracking_exp
  scale: 1.0
  distance_scale: 2.0
