# @package _global_
defaults:
- /scene@env.scene: empty
- /task@env.task: figure8
- /sensor@env.sensor: none
- /observation@env.observation: state_reference
- /execution@env.execution: attitude_thrust
- /objective: tracking_exp
- _self_
env:
  name: tracking
